apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: {{NAMESPACE}}  # Will be replaced with the Kubernetes namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: my-flask-app-container
          image: {{$DOCKER_BFLASK_IMAGE}}  # Will be replaced with the Docker image name (e.g., $DOCKER_BFLASK_IMAGE)
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  namespace: {{NAMESPACE}}  # Will be replaced with the Kubernetes namespace
spec:
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
