---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace:
    "{ NAMESPACE }": null
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: my-flask-app-container
          image:
            "{ $DOCKER_BFLASK_IMAGE }": null
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  namespace:
    "{ NAMESPACE }": null
spec:
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
